<?php get_header() ?>
<main class="main">
    <div class="container">
        <div class="galerija pt-section">
        <div class="galerija__header-wrapper">
                <h1 class="h2--heading mb-64">Galerija slika</h1>
                <img src="/wp-content/themes/aljmas/src/assets/images/gallery-img.png" alt="gallery images"
                    class="gallery__img mb-48" />
        </div>
        <div class="galerija__body-wrapper gap-64 mb-64">
            <div class="galerija__tab">
                <button class="galerija__tab-btn mb-32">
                <img class="gallery-icon" src="/wp-content/themes/aljmas/src/assets/icons/gallery-icon.svg" aria-hidden="true">
                  <span class="galerija__tab-span">Album:</span>'Otvorenje Memorijalnog centra Aljmaš' <img class="close-tab-icon" src="/wp-content/themes/aljmas/src/assets/icons/close-tab-icon.svg" aria-hidden="true">
                </button>
                <div class="galerija__tab-content" data-visible="false">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (1).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (2).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (3).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (4).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (5).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (6).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (7).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (8).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (9).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (10).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (11).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (12).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (13).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (14).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (15).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (16).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (17).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (18).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (19).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (20).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (21).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (22).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (23).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (24).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (25).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (26).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (27).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (28).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (29).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (30).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (31).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (32).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (33).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (34).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (35).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (36).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (37).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (38).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (39).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (40).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (41).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (42).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (43).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (44).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (45).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (46).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (47).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (48).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (49).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (50).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (51).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (52).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (53).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (54).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (55).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (56).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (57).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (58).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (59).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (60).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (61).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (62).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (63).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (64).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (65).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (66).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (67).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (68).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (69).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (70).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (71).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (72).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (73).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (74).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (75).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (76).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (77).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (78).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (79).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (80).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (81).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (82).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (83).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (84).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (85).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (86).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (87).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (88).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (89).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (90).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (91).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (92).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (93).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (94).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (95).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (96).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (97).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (98).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (99).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (100).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (101).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (102).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (103).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (104).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (105).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (106).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (107).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (108).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (109).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (110).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (111).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (112).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (113).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (114).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (115).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (116).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (117).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (118).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (119).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (120).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (121).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (122).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (123).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (124).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (125).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (126).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (127).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (128).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (129).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (130).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (131).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (132).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (133).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (134).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (135).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (136).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (137).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (138).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (139).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (140).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (141).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (142).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (143).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (144).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (145).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (146).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (147).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (148).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (149).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (150).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (151).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (152).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (153).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (154).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (155).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (156).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (157).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (158).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (159).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (160).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (161).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (162).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (163).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (164).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (165).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (166).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (167).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (168).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (169).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (170).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (171).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (172).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (173).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (174).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (175).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (176).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (177).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (178).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (179).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (180).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (181).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (182).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (183).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (184).jpg" alt="image" class="galerija__image">
                </div>
            </div>
            <div class="galerija__tab">
                <button class="galerija__tab-btn mb-32">
                <img class="gallery-icon" src="/wp-content/themes/aljmas/src/assets/icons/gallery-icon.svg" aria-hidden="true">
                  <span class="galerija__tab-span">Album:</span>'Aljmaš i hodočasnici' <img class="close-tab-icon" src="/wp-content/themes/aljmas/src/assets/icons/close-tab-icon.svg" aria-hidden="true">
                </button>
                <div class="galerija__tab-content" data-visible="false">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (185).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (186).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (187).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (188).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (189).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (190).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (191).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (192).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (193).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (194).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (195).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (196).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (197).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (198).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (199).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (200).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (201).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (202).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (203).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (204).jpg" alt="image" class="galerija__image">
                    <img src="/wp-content/themes/aljmas/src/assets/images/album/img (205).jpg" alt="image" class="galerija__image">
                    
                </div>
            </div>
            <div class="galerija__tab">
                <button class="galerija__tab-btn mb-32">
                <img class="gallery-icon" src="/wp-content/themes/aljmas/src/assets/icons/gallery-icon.svg" aria-hidden="true">
                  <span class="galerija__tab-span">Album:</span>'Velika Gospa u Aljmašu' <img class="close-tab-icon" src="/wp-content/themes/aljmas/src/assets/icons/close-tab-icon.svg" aria-hidden="true">
                </button>
                <div class="galerija__tab-content" data-visible="false">
                <img src="/wp-content/themes/aljmas/src/assets/images/album/img (206).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (207).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (208).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (209).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (210).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (211).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (212).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (213).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (214).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (215).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (216).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (217).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (218).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (219).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (220).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (221).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (222).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (223).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (224).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (225).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (226).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (227).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (228).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (229).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (230).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (231).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (232).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (233).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (234).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (235).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (236).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (237).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (238).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (239).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (240).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (241).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (242).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (243).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (244).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (245).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (246).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (247).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (248).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (249).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (250).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (251).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (252).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (253).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (254).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (255).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (256).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (257).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (258).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (259).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (260).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (261).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (262).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (263).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (264).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (265).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (266).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (267).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (268).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (269).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (270).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (271).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (272).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (273).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (274).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (275).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (276).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (277).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (278).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (279).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (280).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (281).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (282).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (283).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (284).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (285).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (286).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (287).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (288).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (289).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (290).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (291).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (292).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (293).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (294).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (295).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (296).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (297).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (298).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (299).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (300).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (301).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (302).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (303).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (304).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (305).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (306).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (307).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (308).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (309).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (310).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (311).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (312).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (313).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (314).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (315).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (316).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (317).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (318).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (319).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (320).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (321).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (322).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (323).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (324).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (325).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (326).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (327).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (328).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (329).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (330).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (331).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (332).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (333).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (334).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (335).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (336).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (337).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (338).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (339).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (340).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (341).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (342).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (343).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (344).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (345).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (346).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (347).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (348).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (349).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (350).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (351).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (352).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (353).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (354).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (355).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (356).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (357).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (358).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (359).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (360).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (361).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (362).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (363).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (364).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (365).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (366).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (367).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (368).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (369).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (370).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (371).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (372).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (373).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (374).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (375).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (376).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (377).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (378).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (379).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (380).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (381).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (382).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (383).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (384).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (385).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (386).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (387).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (388).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (389).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (390).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (391).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (392).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (393).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (394).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (395).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (396).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (397).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (398).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (399).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (400).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (401).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (402).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (403).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (404).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (405).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (406).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (407).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (408).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (409).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (410).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (411).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (412).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (413).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (414).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (415).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (416).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (417).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (418).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (419).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (420).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (421).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (422).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (423).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (424).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (425).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (426).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (427).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (428).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (429).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (430).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (431).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (432).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (433).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (434).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (435).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (436).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (437).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (438).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (439).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (440).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (441).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (442).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (443).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (444).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (445).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (446).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (447).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (448).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (449).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (450).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (451).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (452).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (453).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (454).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (455).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (456).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (457).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (458).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (459).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (460).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (461).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (462).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (463).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (464).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (465).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (466).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (467).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (468).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (469).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (470).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (471).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (472).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (473).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (474).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (475).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (476).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (477).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (478).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (479).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (480).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (481).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (482).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (483).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (484).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (485).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (486).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (487).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (488).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (489).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (490).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (491).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (492).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (493).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (494).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (495).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (496).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (497).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (498).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (499).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (500).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (501).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (502).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (503).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (504).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (505).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (506).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (507).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (508).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (509).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (510).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (511).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (512).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (513).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (514).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (515).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (516).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (517).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (518).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (519).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (520).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (521).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (522).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (523).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (524).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (525).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (526).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (527).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (528).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (529).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (530).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (531).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (532).jpg" alt="image" class="galerija__image">
 <img src="/wp-content/themes/aljmas/src/assets/images/album/img (533).jpg" alt="image" class="galerija__image">
                    
                </div>
            </div>
        </div>
        </div>
    </div>
</main>
<?php get_footer() ?>